apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: opsnexus
  labels:
    app: notification-service
    component: service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
