apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-pv
  namespace: opsnexus
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/opsnexus/localstack
    type: DirectoryOrCreate
  claimRef:
    namespace: opsnexus
    name: localstack-pvc
