apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-pvc
  namespace: opsnexus
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: localstack-pv
