apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: opsnexus
  labels:
    app: localstack
    component: infrastructure
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
    - name: localstack
      port: 4566
      targetPort: 4566
      protocol: TCP
