apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: opsnexus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: opsnexus/${ENVIRONMENT}/rds
