apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "${NODE_ROLE_NAME}"
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        Name: "${PROJECT_NAME}-${ENVIRONMENT}-eks-nodes-sg"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  tags:
    Name: "${PROJECT_NAME}-${ENVIRONMENT}-karpenter-node"
    Environment: "${ENVIRONMENT}"
