apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsnexus

resources:
  - namespace.yaml
  - infrastructure/mysql
  - infrastructure/mongodb
  - infrastructure/localstack
  - services/auth-service
  - services/tenant-service
  - services/workflow-service
  - services/document-service
  - services/notification-service
