aws_region   = "ap-south-1"
aws_profile  = "opsnexus" # Local runs only — CI/CD uses OIDC (leave empty in staging/prod)
project_name = "opsnexus"
environment  = "dev"

# ─── Caylent Tagging ──────────────────────────────────────────────────────────
caylent_owner    = "deepak.saini@caylent.com" # Required
caylent_customer = "OpsNexus"                 # Optional
caylent_workload = "opsnexus-platform"        # Optional
caylent_project  = "opsnexus-platform"        # Optional

# ─── Terraform State ──────────────────────────────────────────────────────────
# State bucket lives in Singapore (created by bootstrap); deploy region is Mumbai
tf_state_bucket = "opsnexus-tf-state"
tf_state_key    = "dev/terraform.tfstate"
tf_state_region = "ap-southeast-1"

# ─── Networking ───────────────────────────────────────────────────────────────
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]

# Public /24 — internet-facing only (ALB, NAT GW)
public_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
# Private EKS /19 — must start at multiples of 32 in octet 3
private_eks_subnet_cidrs = ["10.0.32.0/19", "10.0.64.0/19", "10.0.128.0/19"]
# Private DB /24 — isolated, no overlap with EKS range
private_db_subnet_cidrs = ["10.0.200.0/24", "10.0.201.0/24", "10.0.202.0/24"]

enable_nat_per_az = false # Single NAT gateway — set true for staging/prod HA

# ─── EKS ──────────────────────────────────────────────────────────────────────
# ap-south-1 supports 1.36; staging/prod (ap-southeast-1) cap at 1.35 today
cluster_version            = "1.36"
system_node_instance_types = ["t3.medium"]
system_node_desired        = 2
enable_public_endpoint     = true          # Private-only in prod
public_access_cidrs        = ["0.0.0.0/0"] # Restrict to VPN/office IPs in prod

karpenter_version = "1.13.0"

# ─── RDS ──────────────────────────────────────────────────────────────────────
# db_password is auto-generated and stored in AWS Secrets Manager — not set here
db_instance_class           = "db.t3.small"
db_allocated_storage        = 20
db_max_allocated_storage    = 100
multi_az                    = false # Set true for prod HA
deletion_protection         = false # Set true for prod
skip_final_snapshot         = true  # Set false for prod
backup_retention_period     = 7
enable_performance_insights = false

# ─── DNS / Frontend ───────────────────────────────────────────────────────────
domain_name = "opsnexus.site"

# ─── EKS Admin Access ─────────────────────────────────────────────────────────
# IAM users/roles that get cluster-admin on EKS via Access Entries.
# Run: aws sts get-caller-identity --profile opsnexus --query Arn --output text
admin_iam_arns = [
  "arn:aws:iam::054037129932:user/ab",                          # local dev
  "arn:aws:iam::054037129932:role/opsnexus-github-actions",     # CI/CD
]

# ─── Secrets (managed in AWS Secrets Manager — never in tfvars) ──────────────
# After first apply, set the JWT secret:
#   aws secretsmanager put-secret-value \
#     --secret-id opsnexus/{env}/jwt-secret \
#     --secret-string "$(openssl rand -base64 48)"
#
# All other secrets (RDS password, API keys) are auto-generated by Terraform.
